"""7-point Laplacian stencil kernel.

Generated by derivations/laplacian_stencil.py. Do not edit by hand.
Regenerate with: python scripts/generate_kernels.py

Function:
    domain   — (fields: Array of field arrays on Ω_h ⊆ ℤ³, extent: Extent)
    codomain — un-divided stencil sum L_h[φ] on the interior of Ω_h
    operator — seven-point finite-difference Laplacian, Θ = (radii=(1,1,1)), p = 2
"""

from __future__ import annotations

import hashlib
from typing import Any

from cosmic_foundry.computation.stencil import Stencil

_COEFFICIENTS_HASH = "09f7d863bad077c7"

CENTER_WEIGHT: int = -6
NEIGHBOR_WEIGHT: int = 1
APPROXIMATION_ORDER: int = 2

_canonical = (
    f"CENTER_WEIGHT={CENTER_WEIGHT};"
    f"NEIGHBOR_WEIGHT={NEIGHBOR_WEIGHT};"
    f"APPROXIMATION_ORDER={APPROXIMATION_ORDER}"
)
assert hashlib.sha256(_canonical.encode()).hexdigest()[:16] == _COEFFICIENTS_HASH, (
    "Kernel coefficients do not match the embedded derivation hash. "
    "Regenerate with: python scripts/generate_kernels.py"
)


def _seven_point_fn(fields: tuple[Any, ...], i: Any, j: Any, k: Any) -> Any:
    phi = fields[0]
    return (
        NEIGHBOR_WEIGHT * phi[i - 1, j, k]
        + NEIGHBOR_WEIGHT * phi[i + 1, j, k]
        + NEIGHBOR_WEIGHT * phi[i, j - 1, k]
        + NEIGHBOR_WEIGHT * phi[i, j + 1, k]
        + NEIGHBOR_WEIGHT * phi[i, j, k - 1]
        + NEIGHBOR_WEIGHT * phi[i, j, k + 1]
        + CENTER_WEIGHT * phi[i, j, k]
    )


seven_point_laplacian = Stencil(fn=_seven_point_fn, radii=(1, 1, 1))
