"""Theory layer: abstract mathematical structure.

Contains foundation/, continuous/, and discrete/ — the symbolic-reasoning
layers. Everything in theory/ describes mathematical structure symbolically,
without numerical evaluation.

Boundary rule: may only import from stdlib, cosmic_foundry, or the approved
symbolic-reasoning packages {sympy}.
"""

from __future__ import annotations

from cosmic_foundry.theory.continuous import (
    AdvectionDiffusionOperator,
    AdvectionOperator,
    Atlas,
    BoundaryCondition,
    Chart,
    Constraint,
    Diffeomorphism,
    DifferentialForm,
    DifferentialOperator,
    DiffusionOperator,
    DirichletBC,
    DivergenceFormEquation,
    ExteriorDerivative,
    Field,
    LocalBoundaryCondition,
    Manifold,
    MetricTensor,
    NonLocalBoundaryCondition,
    OneForm,
    PeriodicBC,
    Point,
    PoissonEquation,
    PseudoRiemannianManifold,
    RiemannianManifold,
    SymbolicFunction,
    SymmetricTensorField,
    TensorField,
    ThreeForm,
    TopologicalManifold,
    TwoForm,
    ZeroForm,
)
from cosmic_foundry.theory.discrete import (
    CellComplex,
    DirichletGhostCells,
    DiscreteBoundaryCondition,
    DiscreteExteriorDerivative,
    DiscreteField,
    DiscreteOperator,
    Discretization,
    DivergenceFormDiscretization,
    EdgeField,
    FaceField,
    Mesh,
    NumericalFlux,
    PeriodicGhostCells,
    PointField,
    RestrictionOperator,
    StructuredMesh,
    VolumeField,
    ZeroGhostCells,
)
from cosmic_foundry.theory.foundation import (
    Function,
    Homeomorphism,
    IndexedFamily,
    IndexedSet,
    InvertibleFunction,
    NumericFunction,
    Set,
    TopologicalSpace,
)

__all__ = [
    # continuous
    "AdvectionDiffusionOperator",
    "AdvectionOperator",
    "Atlas",
    "BoundaryCondition",
    "Chart",
    "Constraint",
    "Diffeomorphism",
    "DifferentialForm",
    "DifferentialOperator",
    "DiffusionOperator",
    "DirichletBC",
    "DivergenceFormEquation",
    "ExteriorDerivative",
    "Field",
    "LocalBoundaryCondition",
    "Manifold",
    "MetricTensor",
    "NonLocalBoundaryCondition",
    "OneForm",
    "PeriodicBC",
    "Point",
    "PoissonEquation",
    "PseudoRiemannianManifold",
    "RiemannianManifold",
    "SymbolicFunction",
    "SymmetricTensorField",
    "TensorField",
    "ThreeForm",
    "TopologicalManifold",
    "TwoForm",
    "ZeroForm",
    # discrete
    "CellComplex",
    "DirichletGhostCells",
    "DiscreteBoundaryCondition",
    "DiscreteExteriorDerivative",
    "DiscreteField",
    "DiscreteOperator",
    "Discretization",
    "DivergenceFormDiscretization",
    "EdgeField",
    "FaceField",
    "Mesh",
    "NumericalFlux",
    "PeriodicGhostCells",
    "PointField",
    "RestrictionOperator",
    "StructuredMesh",
    "VolumeField",
    "ZeroGhostCells",
    # foundation
    "Function",
    "Homeomorphism",
    "IndexedFamily",
    "IndexedSet",
    "InvertibleFunction",
    "NumericFunction",
    "Set",
    "TopologicalSpace",
]
